Feature/app header
YuvalLeviMoveoHLS/Dispatcher_Frontend pull request #3
Opened 2023-08-28 19:16 UTC by YuvalLeviMoveoHLS

2023-08-29 08:56 UTC, ZivCohenMoveo requested changes

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/AppHeader/appHeader.tsx
> +        {isDropdownVisible && <RecentSearchDropdown ref={dropdownRef} />}
put it together in component of `DropdownWithSearch` and change the `RecentSearchDropdown` name to `DropdownBody` or something like this

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/AppHeader/appHeader.tsx
> +        {isDropdownVisible && <RecentSearchDropdown ref={dropdownRef} />}
And move all the logic in lines 13-33 inside `DropdownWithSearch` component

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/AppHeader/appHeader.stories.ts
Components name should be in title case
Fix it in all files

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/AppHeader/appHeader.tsx
> +      console.log(dropdownRef.current.contains(event.target as Node));
remove

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/Input/searchInput.tsx
> +        ></FilterDropDown>
Shouldn't be inside SearchInput
SearchInput should be only the input itself
The input and the dropdown together should be in different component like `DropdownWithSearch`

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/RecentSearchDropdown/RecentSearchDropdown.tsx
> +  );
You don't need useState.

```suggestion
  const recentSearches = props.searches ?? recentSearchesMock
```

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/components/RecentSearchDropdown/RecentSearchDropdown.stories.ts
> +    searches: ["crypto", "soccer", "basketball", "NBA"],
use `recentSearchesMock`

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/utils/constants/maxValues.ts
> +export const MAX_AMOUNT_RECENT_SEARCHES = 5;
in use?

2023-08-29 08:56 UTC, ZivCohenMoveo commented on src/styles/globalStyles.ts
> +export const AppContainer = styled.div`
move it to `App.styles.ts`

2023-08-30 12:38 UTC, ronc1812 approved these changes

2023-08-30 12:44 UTC, merged